export const ROUTES = {
  LOGIN: "/login",
  AUTH_CALLBACK: "/auth/callback",
  DASHBOARD: "/",
  STOCKS: "/stocks",
  STOCK_DETAIL: "/stocks/:code",
  ETF: "/etf",
  ETF_DETAIL: "/etf/:code",
  REIT: "/reit",
  REIT_DETAIL: "/reit/:code",
  CALCULATE: "/valuations/calculate",
  VALUATIONS: "/valuations",
  VALUATION_DETAIL: "/valuations/:id",
  WATCHLIST: "/watchlist",
  PORTFOLIO: "/portfolio",
  PORTFOLIO_STOCKS: "/portfolio?tab=stocks",
  PORTFOLIO_ACCOUNT_INPUT: "/portfolio/accounts/:id/input",
  PORTFOLIO_SHARE: "/portfolio/share",
  PAPER_TRADING: "/paper-trading",
  FX: "/fx",
  NEWS: "/news",
  WIKI: "/wiki",
  CHAT: "/chat",
  SETTINGS: "/settings",
  ADMIN_USERS: "/admin/users",
} as const;
