# Generated by Django 6.0.2 on 2026-05-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndustryMetrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sector", models.CharField(max_length=100, unique=True, verbose_name="業種")),
                ("min_roe", models.DecimalField(decimal_places=4, max_digits=8, verbose_name="下限ROE")),
                ("max_roe", models.DecimalField(decimal_places=4, max_digits=8, verbose_name="上限ROE")),
                ("note", models.CharField(blank=True, default="", max_length=255, verbose_name="メモ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "業界指標",
                "verbose_name_plural": "業界指標",
                "db_table": "m_industry_metrics",
                "ordering": ["sector"],
            },
        ),
    ]
