# Generated by Django 6.0.2 on 2026-05-02 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("portfolios", "0008_accountholding_proxy_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="目標名")),
                ("target_value_jpy", models.DecimalField(decimal_places=0, max_digits=16, verbose_name="目標金額(円)")),
                ("target_date", models.DateField(verbose_name="達成目標日（月初固定）")),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("family", "家族合計"), ("members", "メンバー指定")],
                        max_length=20,
                        verbose_name="スコープ種別",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "金融目標",
                "verbose_name_plural": "金融目標",
                "db_table": "m_financial_goals",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "family_member",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="portfolios.familymember"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_links",
                        to="goals.financialgoal",
                    ),
                ),
            ],
            options={
                "verbose_name": "目標メンバー",
                "verbose_name_plural": "目標メンバー",
                "db_table": "r_goal_members",
                "unique_together": {("goal", "family_member")},
            },
        ),
    ]
