# Generated by Django 6.0.2 on 2026-05-02 08:48

from django.db import migrations, models


def initialize_display_order(apps, schema_editor):
    """既存レコードに対して、ユーザーごとに id 順で 0,1,2... を割り振る。"""
    FinancialGoal = apps.get_model("goals", "FinancialGoal")
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        for idx, goal in enumerate(FinancialGoal.objects.filter(user_id=user.pk).order_by("id")):
            goal.display_order = idx
            goal.save(update_fields=["display_order"])


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialgoal",
            options={
                "ordering": ["display_order", "id"],
                "verbose_name": "金融目標",
                "verbose_name_plural": "金融目標",
            },
        ),
        migrations.AddField(
            model_name="financialgoal",
            name="display_order",
            field=models.IntegerField(default=0, verbose_name="表示順"),
        ),
        migrations.RunPython(initialize_display_order, reverse_code=migrations.RunPython.noop),
    ]
