# Generated by Django 6.0.2 on 2026-02-28 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stocks", "0009_stockfinancial_period_end_date_stockprice_adj_factor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiAnalysisLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("pbr_low", "PBR低位の理由"),
                            ("investment_risk", "投資リスク"),
                            ("growth_outlook", "成長見通し"),
                            ("custom", "カスタム質問"),
                        ],
                        max_length=30,
                        verbose_name="質問タイプ",
                    ),
                ),
                ("custom_question", models.TextField(blank=True, default="", verbose_name="カスタム質問")),
                ("model_used", models.CharField(max_length=100, verbose_name="使用モデル")),
                ("prompt_tokens", models.IntegerField(default=0, verbose_name="プロンプトトークン数")),
                ("completion_tokens", models.IntegerField(default=0, verbose_name="補完トークン数")),
                ("is_success", models.BooleanField(default=True, verbose_name="成功フラグ")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="エラーメッセージ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="実行日時")),
                (
                    "stock",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_analysis_logs",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI分析ログ",
                "verbose_name_plural": "AI分析ログ",
                "db_table": "t_ai_analysis_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAiConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI")], default="openai", max_length=50, verbose_name="プロバイダー"
                    ),
                ),
                ("api_key", models.CharField(blank=True, default="", max_length=500, verbose_name="APIキー")),
                ("model", models.CharField(default="gpt-4o-mini", max_length=100, verbose_name="使用モデル")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="有効フラグ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_config",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザーAI設定",
                "verbose_name_plural": "ユーザーAI設定",
                "db_table": "m_user_ai_configs",
            },
        ),
    ]
