# Generated by Django 6.0.2 on 2026-05-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_update_default_model_to_gemini25_flash"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysislog",
            name="expert_role",
            field=models.CharField(
                choices=[
                    ("general", "汎用アナリスト"),
                    ("quant", "クオンツ"),
                    ("fundamental", "ファンダメンタルズ"),
                    ("macro", "マクロ"),
                    ("technical", "テクニカル"),
                    ("risk_mgmt", "リスク管理"),
                ],
                default="general",
                max_length=20,
                verbose_name="専門家ロール",
            ),
        ),
    ]
