# Generated by Django 6.0.2 on 2026-05-18 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0004_aianalysislog_expert_role"),
        ("stocks", "0016_stockprice_is_limit_down_stockprice_is_limit_up_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "decision_type",
                    models.CharField(
                        choices=[("buy", "買い"), ("sell", "売り"), ("hold", "保有継続"), ("watch", "ウォッチ")],
                        max_length=20,
                        verbose_name="判断種別",
                    ),
                ),
                ("rationale", models.TextField(help_text="AI が生成した自由テキスト", verbose_name="判断根拠")),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0.00〜1.00（任意）",
                        max_digits=3,
                        null=True,
                        verbose_name="確信度",
                    ),
                ),
                (
                    "snapshot_indicators",
                    models.JSONField(
                        default=dict,
                        help_text="get_stock_summary 結果のスナップショット",
                        verbose_name="判断時点のスナップショット",
                    ),
                ),
                ("ai_model", models.CharField(blank=True, default="", max_length=100, verbose_name="AI モデル")),
                ("decided_at", models.DateTimeField(auto_now_add=True, verbose_name="判断日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_decisions",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 判断履歴",
                "verbose_name_plural": "AI 判断履歴",
                "db_table": "t_ai_decisions",
                "ordering": ["-decided_at"],
                "indexes": [
                    models.Index(fields=["user", "-decided_at"], name="idx_aidec_user_decided"),
                    models.Index(fields=["stock", "-decided_at"], name="idx_aidec_stock_decided"),
                ],
            },
        ),
    ]
