# Generated by Django 6.0.2 on 2026-02-25 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stocks", "0003_apiconfig_synclog_stock_is_active_stock_market_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("nisa_growth", "NISA成長投資枠"),
                            ("nisa_reserve", "NISAつみたて投資枠"),
                            ("specific", "特定口座"),
                            ("general", "一般口座"),
                            ("us_securities", "米国証券口座"),
                        ],
                        default="specific",
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("average_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("purchased_at", models.DateField()),
                ("memo", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_items", to="stocks.stock"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "t_portfolio_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("memo", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="watchlist_items", to="stocks.stock"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "r_watchlist",
                "ordering": ["-created_at"],
                "unique_together": {("user", "stock")},
            },
        ),
    ]
