# Generated by Django 6.0.2 on 2026-02-26 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_date", models.DateField(verbose_name="記録日")),
                ("total_value_jpy", models.DecimalField(decimal_places=0, max_digits=16, verbose_name="評価額(円)")),
                (
                    "total_cost_jpy",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=16, null=True, verbose_name="取得原価(円)"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="為替レート"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "月次スナップショット",
                "verbose_name_plural": "月次スナップショット",
                "db_table": "t_account_snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="AccountHolding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ticker_code", models.CharField(blank=True, max_length=20, verbose_name="ティッカー")),
                ("asset_name", models.CharField(max_length=255, verbose_name="銘柄・商品名")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("stock", "株式"),
                            ("etf", "ETF"),
                            ("fund", "投資信託"),
                            ("bond", "債券"),
                            ("cash", "現金"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="資産種別",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name="数量"),
                ),
                (
                    "unit_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name="単価"),
                ),
                ("value_jpy", models.DecimalField(decimal_places=0, max_digits=16, verbose_name="評価額(円)")),
                (
                    "cost_jpy",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=16, null=True, verbose_name="取得原価(円)"
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="portfolios.accountsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "個別保有明細",
                "verbose_name_plural": "個別保有明細",
                "db_table": "t_account_holdings",
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="名前")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("self", "本人"),
                            ("spouse", "配偶者"),
                            ("child", "子"),
                            ("parent", "親"),
                            ("other", "その他"),
                        ],
                        default="self",
                        max_length=20,
                        verbose_name="役割",
                    ),
                ),
                ("color_code", models.CharField(default="#1976d2", max_length=7, verbose_name="カラーコード")),
                ("display_order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "家族メンバー",
                "verbose_name_plural": "家族メンバー",
                "db_table": "m_family_members",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("institution", models.CharField(max_length=100, verbose_name="機関名")),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("securities_jp", "国内証券"),
                            ("securities_us", "米国証券"),
                            ("bank", "銀行"),
                            ("ideco", "iDeCo"),
                            ("mutual_aid", "小規模企業共済"),
                            ("company_loan", "会社貸付"),
                            ("insurance", "保険"),
                            ("pension", "年金"),
                            ("other", "その他"),
                        ],
                        max_length=30,
                        verbose_name="機関種別",
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("cash", "現金・預金"),
                            ("jp_stock", "国内株式"),
                            ("us_stock", "米国株式"),
                            ("jp_bond", "国内債券"),
                            ("us_bond", "米国債"),
                            ("etf", "ETF"),
                            ("fund", "投資信託"),
                            ("insurance", "保険"),
                            ("loan", "貸付"),
                            ("other", "その他"),
                        ],
                        max_length=30,
                        verbose_name="資産クラス",
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=100, verbose_name="表示名")),
                ("currency", models.CharField(default="JPY", max_length=3, verbose_name="通貨")),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "family_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="portfolios.familymember",
                    ),
                ),
            ],
            options={
                "verbose_name": "口座",
                "verbose_name_plural": "口座",
                "db_table": "m_portfolio_accounts",
                "ordering": ["family_member__display_order", "institution"],
            },
        ),
        migrations.AddField(
            model_name="accountsnapshot",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="portfolios.portfolioaccount"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountsnapshot",
            unique_together={("account", "snapshot_date")},
        ),
    ]
