# Generated by Django 6.0.2 on 2026-03-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0002_accountsnapshot_accountholding_familymember_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="include_in_family_total",
            field=models.BooleanField(default=True, verbose_name="家族合算に含める"),
        ),
        migrations.AlterField(
            model_name="portfolioaccount",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("cash", "現金・預金"),
                    ("jp_stock", "国内株式"),
                    ("us_stock", "米国株式"),
                    ("jp_bond", "国内債券"),
                    ("us_bond", "米国債"),
                    ("etf", "ETF"),
                    ("fund", "投資信託"),
                    ("insurance", "保険"),
                    ("loan", "貸付"),
                    ("real_estate", "不動産・土地"),
                    ("other", "その他"),
                ],
                max_length=30,
                verbose_name="資産クラス",
            ),
        ),
    ]
