# Generated by Django 6.0.2 on 2026-03-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0003_add_family_total_flag_and_real_estate"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioaccount",
            name="trading_type",
            field=models.CharField(
                choices=[("spot", "現物"), ("margin", "信用")],
                default="spot",
                max_length=20,
                verbose_name="取引方式",
            ),
        ),
    ]
