# Generated by Django 6.0.2 on 2026-03-09 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0004_add_trading_type"),
        ("stocks", "0009_stockfinancial_period_end_date_stockprice_adj_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountholding",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_holdings",
                to="stocks.stock",
                verbose_name="銘柄",
            ),
        ),
    ]
