# Generated by Django 6.0.2 on 2026-03-09 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0005_add_stock_to_account_holding"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PortfolioItem",
        ),
    ]
