# Generated by Django 6.0.2 on 2026-03-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0006_remove_portfolio_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioaccount",
            name="expected_return_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="期待リターン率(%)"
            ),
        ),
    ]
