# Generated by Django 6.0.2 on 2026-05-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0008_accountholding_proxy_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioaccount",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("cash", "現金・預金"),
                    ("jp_stock", "国内株式"),
                    ("us_stock", "米国株式"),
                    ("jp_bond", "国内債券"),
                    ("us_bond", "米国債"),
                    ("etf", "ETF"),
                    ("fund", "投資信託"),
                    ("insurance", "保険"),
                    ("mutual_aid", "共済"),
                    ("loan", "貸付"),
                    ("real_estate", "不動産・土地"),
                    ("other", "その他"),
                ],
                max_length=30,
                verbose_name="資産クラス",
            ),
        ),
    ]
