# Generated by Django 6.0.2 on 2026-05-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0009_alter_portfolioaccount_asset_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountholding",
            name="built_date",
            field=models.DateField(
                blank=True,
                help_text="信用建玉の建玉日。未設定時は snapshot_date を fallback として扱う",
                null=True,
                verbose_name="建玉日",
            ),
        ),
        migrations.AddField(
            model_name="portfolioaccount",
            name="margin_credit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("system_6m", "制度信用 (6ヶ月)"),
                    ("general_6m", "一般信用 (6ヶ月)"),
                    ("general_unlimited", "一般信用 (無期限)"),
                ],
                help_text="trading_type=margin のときに設定。期限・現引き計算に使用",
                max_length=30,
                null=True,
                verbose_name="信用枠区分",
            ),
        ),
        migrations.AddField(
            model_name="portfolioaccount",
            name="margin_interest_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="例: 0.0285 = 年率 2.85%",
                max_digits=5,
                null=True,
                verbose_name="信用金利 (年率)",
            ),
        ),
    ]
