# Generated by Django 6.0.2 on 2026-02-25 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=10, unique=True, verbose_name="証券コード")),
                ("name", models.CharField(max_length=255, verbose_name="銘柄名")),
                ("market", models.CharField(blank=True, default="", max_length=50, verbose_name="市場区分")),
                ("sector", models.CharField(blank=True, default="", max_length=100, verbose_name="業種")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "銘柄",
                "verbose_name_plural": "銘柄",
                "db_table": "stocks",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StockFinancial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fiscal_year", models.IntegerField(verbose_name="会計年度")),
                ("bps", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="1株あたり純資産(BPS)")),
                (
                    "eps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="1株あたり利益(EPS)"
                    ),
                ),
                ("roe", models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="ROE")),
                ("net_assets", models.BigIntegerField(blank=True, null=True, verbose_name="純資産(百万円)")),
                ("total_shares", models.BigIntegerField(blank=True, null=True, verbose_name="発行済株式数")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "財務データ",
                "verbose_name_plural": "財務データ",
                "db_table": "stock_financials",
                "ordering": ["-fiscal_year"],
                "unique_together": {("stock", "fiscal_year")},
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="日付")),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="終値")),
                ("pbr", models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="PBR")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "株価",
                "verbose_name_plural": "株価",
                "db_table": "stock_prices",
                "ordering": ["-date"],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
