# Generated by Django 6.0.2 on 2026-02-25 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="stock",
            table="m_stocks",
        ),
        migrations.AlterModelTable(
            name="stockfinancial",
            table="t_stock_financials",
        ),
        migrations.AlterModelTable(
            name="stockprice",
            table="t_stock_prices",
        ),
    ]
