# Generated by Django 6.0.2 on 2026-02-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_alter_stock_table_alter_stockfinancial_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=50, unique=True, verbose_name="プロバイダー")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="有効フラグ")),
                ("api_key", models.CharField(blank=True, default="", max_length=500, verbose_name="APIキー")),
                ("plan", models.CharField(blank=True, default="", max_length=50, verbose_name="契約プラン")),
                ("config_json", models.JSONField(blank=True, default=dict, verbose_name="追加設定")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "API設定",
                "verbose_name_plural": "API設定",
                "db_table": "m_api_configs",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("stocks", "銘柄マスタ"), ("financials", "財務データ"), ("prices", "株価")],
                        max_length=20,
                        verbose_name="同期種別",
                    ),
                ),
                ("provider", models.CharField(max_length=50, verbose_name="データソース")),
                ("market", models.CharField(blank=True, default="", max_length=10, verbose_name="市場")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "実行中"),
                            ("success", "成功"),
                            ("partial", "一部失敗"),
                            ("failed", "失敗"),
                        ],
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="開始日時")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="終了日時")),
                ("total_count", models.IntegerField(default=0, verbose_name="対象件数")),
                ("success_count", models.IntegerField(default=0, verbose_name="成功件数")),
                ("error_count", models.IntegerField(default=0, verbose_name="エラー件数")),
                ("error_details", models.JSONField(blank=True, default=list, verbose_name="エラー詳細")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
            ],
            options={
                "verbose_name": "同期ログ",
                "verbose_name_plural": "同期ログ",
                "db_table": "t_sync_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="有効フラグ"),
        ),
        migrations.AddField(
            model_name="stock",
            name="market_type",
            field=models.CharField(
                choices=[("JP", "日本"), ("US", "米国")], default="JP", max_length=2, verbose_name="市場タイプ"
            ),
        ),
        migrations.AddField(
            model_name="stockfinancial",
            name="operating_income",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="営業利益(百万円)"),
        ),
        migrations.AddField(
            model_name="stockfinancial",
            name="revenue",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="売上高(百万円)"),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="出来高"),
        ),
    ]
