# Generated by Django 6.0.2 on 2026-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_apiconfig_synclog_stock_is_active_stock_market_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="latest_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="最新株価"),
        ),
        migrations.AddField(
            model_name="stock",
            name="latest_price_date",
            field=models.DateField(blank=True, null=True, verbose_name="最新株価日"),
        ),
    ]
