# Generated by Django 6.0.2 on 2026-02-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0004_add_latest_price_to_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockfinancial",
            name="eps_forecast",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="予想EPS"),
        ),
    ]
