# Generated by Django 6.0.2 on 2026-02-26 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0005_stockfinancial_eps_forecast"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="instrument_type",
            field=models.CharField(
                choices=[("stock", "普通株式"), ("etf", "ETF・ETN"), ("reit", "J-REIT"), ("other", "その他")],
                default="stock",
                max_length=10,
                verbose_name="種別",
            ),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="sync_type",
            field=models.CharField(
                choices=[
                    ("stocks", "銘柄マスタ"),
                    ("financials", "財務データ"),
                    ("prices", "株価"),
                    ("dividends", "配当・分配金"),
                ],
                max_length=20,
                verbose_name="同期種別",
            ),
        ),
        migrations.CreateModel(
            name="Dividend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ex_dividend_date", models.DateField(verbose_name="権利落ち日")),
                (
                    "dividends_per_share",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="1口あたり配当/分配金"),
                ),
                ("record_date", models.DateField(blank=True, null=True, verbose_name="権利確定日")),
                ("payable_date", models.DateField(blank=True, null=True, verbose_name="支払開始日")),
                ("source", models.CharField(default="yfinance", max_length=20, verbose_name="取得元")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividends",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "配当・分配金",
                "verbose_name_plural": "配当・分配金",
                "db_table": "t_dividends",
                "ordering": ["-ex_dividend_date"],
                "unique_together": {("stock", "ex_dividend_date")},
            },
        ),
    ]
