# Generated by Django 6.0.2 on 2026-02-27 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0006_stock_instrument_type_alter_synclog_sync_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="consecutive_missing_syncs",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="J-Quantsレスポンスに連続で含まれなかった回数", verbose_name="連続欠損同期回数"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="is_active_override",
            field=models.BooleanField(
                blank=True,
                help_text="True=強制アクティブ, False=強制非アクティブ, Null=自動判定(sync準拠)",
                null=True,
                verbose_name="上場状態手動オーバーライド",
            ),
        ),
        migrations.CreateModel(
            name="FinancialManualInput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fiscal_year", models.IntegerField(verbose_name="会計年度")),
                (
                    "bps",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="BPS"),
                ),
                (
                    "eps",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="EPS"),
                ),
                ("roe", models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="ROE")),
                (
                    "eps_forecast",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="予想EPS"),
                ),
                ("revenue", models.BigIntegerField(blank=True, null=True, verbose_name="売上高(百万円)")),
                ("operating_income", models.BigIntegerField(blank=True, null=True, verbose_name="営業利益(百万円)")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("shikiho", "四季報"),
                            ("minkabu", "ミンカブ"),
                            ("irpage", "IR/会社HP"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="情報ソース",
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="メモ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_financials",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "手動入力財務データ",
                "verbose_name_plural": "手動入力財務データ",
                "db_table": "t_financial_manual_inputs",
                "ordering": ["-fiscal_year"],
                "unique_together": {("stock", "fiscal_year")},
            },
        ),
    ]
