# Generated by Django 6.0.2 on 2026-02-27 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0007_add_is_active_override_and_manual_financial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarginBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="公表日")),
                ("long_balance", models.BigIntegerField(blank=True, null=True, verbose_name="信用買残(株数)")),
                (
                    "long_balance_change",
                    models.BigIntegerField(blank=True, null=True, verbose_name="信用買残変化(株数)"),
                ),
                ("short_balance", models.BigIntegerField(blank=True, null=True, verbose_name="信用売残(株数)")),
                (
                    "short_balance_change",
                    models.BigIntegerField(blank=True, null=True, verbose_name="信用売残変化(株数)"),
                ),
                (
                    "sl_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="信用売残÷信用買残",
                        max_digits=8,
                        null=True,
                        verbose_name="信売比率",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="margin_balances",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "信用残高",
                "verbose_name_plural": "信用残高",
                "db_table": "t_margin_balances",
                "ordering": ["-date"],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
