# Generated by Django 6.0.2 on 2026-02-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0008_add_margin_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockfinancial",
            name="period_end_date",
            field=models.DateField(
                blank=True,
                help_text="J-Quants CurPerEn: 株式分割調整係数の基準日",
                null=True,
                verbose_name="決算期末日",
            ),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="adj_factor",
            field=models.DecimalField(
                decimal_places=10,
                default=1,
                help_text="株式分割等の権利調整係数（AdjFactor）。現在日は1.0、分割前は<1.0",
                max_digits=20,
                verbose_name="調整係数",
            ),
        ),
    ]
