# Generated by Django 6.0.2 on 2026-03-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0009_stockfinancial_period_end_date_stockprice_adj_factor"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stockprice",
            index=models.Index(fields=["date", "stock"], name="idx_price_date_stock"),
        ),
    ]
