# Generated by Django 6.0.2 on 2026-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0010_add_date_index_to_stock_prices"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stockfinancial",
            index=models.Index(fields=["stock", "-fiscal_year"], name="idx_financial_stock_fy"),
        ),
    ]
