# Generated by Django 6.0.2 on 2026-03-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0011_add_financial_stock_fy_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerShareholder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("representative_name", models.CharField(max_length=100, verbose_name="代表者氏名")),
                ("shareholder_name", models.CharField(max_length=200, verbose_name="大株主名")),
                ("shareholder_rank", models.IntegerField(verbose_name="大株主順位")),
                ("ownership_ratio", models.DecimalField(decimal_places=2, max_digits=6, verbose_name="持ち株比率(%)")),
                (
                    "match_type",
                    models.CharField(
                        choices=[("exact", "代表者本人"), ("family", "親族（同姓）"), ("company", "資産管理会社候補")],
                        max_length=20,
                        verbose_name="判定タイプ",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="事業年度")),
                ("doc_id", models.CharField(max_length=20, verbose_name="EDINET書類ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_shareholders",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "オーナー大株主",
                "verbose_name_plural": "オーナー大株主",
                "db_table": "t_owner_shareholders",
                "ordering": ["-fiscal_year", "shareholder_rank"],
                "unique_together": {("stock", "fiscal_year", "shareholder_rank")},
            },
        ),
        migrations.CreateModel(
            name="ShareholderRaw",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("shareholder_name", models.CharField(max_length=200, verbose_name="大株主名")),
                ("shareholder_rank", models.IntegerField(verbose_name="順位")),
                ("ownership_ratio", models.DecimalField(decimal_places=2, max_digits=6, verbose_name="持ち株比率(%)")),
                ("shares_held", models.BigIntegerField(blank=True, null=True, verbose_name="保有株数")),
                ("fiscal_year", models.IntegerField(verbose_name="事業年度")),
                ("doc_id", models.CharField(max_length=20, verbose_name="EDINET書類ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareholders_raw",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "大株主生データ",
                "verbose_name_plural": "大株主生データ",
                "db_table": "t_shareholder_raw",
                "ordering": ["-fiscal_year", "shareholder_rank"],
                "unique_together": {("stock", "fiscal_year", "shareholder_rank")},
            },
        ),
    ]
