# Generated by Django 6.0.2 on 2026-03-24 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0012_add_owner_shareholder_tables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="プリセット名")),
                ("priority", models.IntegerField(default=0, help_text="小さいほど優先", verbose_name="優先度")),
                ("filters", models.JSONField(default=dict, verbose_name="フィルター設定")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_presets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "スクリーニングプリセット",
                "verbose_name_plural": "スクリーニングプリセット",
                "db_table": "m_user_screening_presets",
                "ordering": ["priority", "created_at"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
