# Generated by Django 6.0.2 on 2026-03-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0013_add_screening_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockfinancial",
            name="free_cash_flow",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="FCF(百万円)"),
        ),
        migrations.AddField(
            model_name="stockfinancial",
            name="operating_cash_flow",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="営業CF(百万円)"),
        ),
    ]
