# Generated by Django 6.0.2 on 2026-05-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0014_add_cash_flow_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[("long_term", "長期保有"), ("day_trade", "デイトレ"), ("range_bound", "1〜2年レンジ")],
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(verbose_name="順位")),
                (
                    "latest_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="最新株価"
                    ),
                ),
                ("metrics", models.JSONField(default=dict, verbose_name="指標")),
                ("score", models.DecimalField(decimal_places=4, max_digits=14, verbose_name="スコア")),
                ("generated_at", models.DateTimeField(auto_now_add=True, verbose_name="生成日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_snapshots",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "おすすめ銘柄スナップショット",
                "verbose_name_plural": "おすすめ銘柄スナップショット",
                "db_table": "t_recommendation_snapshots",
                "ordering": ["category", "rank"],
                "indexes": [models.Index(fields=["category", "rank"], name="t_recommend_categor_5545c6_idx")],
                "unique_together": {("category", "rank")},
            },
        ),
    ]
