# Generated by Django 6.0.2 on 2026-05-18 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0015_recommendationsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockprice",
            name="is_limit_down",
            field=models.BooleanField(default=False, help_text="J-Quants LL フラグ", verbose_name="ストップ安"),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="is_limit_up",
            field=models.BooleanField(default=False, help_text="J-Quants UL フラグ", verbose_name="ストップ高"),
        ),
        migrations.CreateModel(
            name="DailyMovers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="集計日")),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="終値")),
                (
                    "prev_close",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="前営業日終値"
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="例: 21.2800",
                        max_digits=8,
                        null=True,
                        verbose_name="前日比(%)",
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True, verbose_name="出来高")),
                (
                    "volume_ratio_20d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="例: 3.80",
                        max_digits=8,
                        null=True,
                        verbose_name="出来高 20 日平均比",
                    ),
                ),
                ("is_limit_up", models.BooleanField(default=False, verbose_name="ストップ高")),
                ("is_limit_down", models.BooleanField(default=False, verbose_name="ストップ安")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_movers",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "日次急騰急落",
                "verbose_name_plural": "日次急騰急落",
                "db_table": "t_daily_movers",
                "ordering": ["-date", "-change_pct"],
                "indexes": [
                    models.Index(fields=["date", "change_pct"], name="idx_movers_date_change"),
                    models.Index(fields=["date", "volume_ratio_20d"], name="idx_movers_date_volratio"),
                ],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
