# Generated by Django 6.0.2 on 2026-05-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0016_stockprice_is_limit_down_stockprice_is_limit_up_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(fields=["-started_at"], name="t_sync_logs_started_idx"),
        ),
    ]
