# Generated by Django 6.0.2 on 2026-08-15 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0017_synclog_t_sync_logs_started_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=16, verbose_name="証券コード")),
                ("name", models.CharField(max_length=255, verbose_name="銘柄名")),
                ("sector", models.CharField(blank=True, max_length=100, verbose_name="業種")),
                ("market_type", models.CharField(default="JP", max_length=8, verbose_name="市場区分")),
                ("is_active", models.BooleanField(default=True, verbose_name="上場中")),
                (
                    "roe",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name="ROE"),
                ),
                (
                    "sl_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True, verbose_name="信売比率"
                    ),
                ),
                ("roe_trend", models.CharField(blank=True, max_length=16, null=True, verbose_name="ROEトレンド")),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="配当利回り"
                    ),
                ),
                (
                    "fcf_yield",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="FCF利回り"
                    ),
                ),
                ("momentum_signal", models.CharField(blank=True, max_length=16, null=True, verbose_name="モメンタム")),
                ("liquidity_level", models.CharField(blank=True, max_length=16, null=True, verbose_name="流動性")),
                ("is_owner_managed", models.BooleanField(default=False, verbose_name="オーナー経営")),
                ("ma_golden_cross", models.BooleanField(default=False)),
                ("price_cross_ma25", models.BooleanField(default=False)),
                ("price_cross_ma75", models.BooleanField(default=False)),
                ("macd_golden_cross", models.BooleanField(default=False)),
                ("rsi_rebound", models.BooleanField(default=False)),
                ("pullback_buy", models.BooleanField(default=False)),
                ("metrics", models.JSONField(default=dict, verbose_name="その他指標")),
                ("generated_at", models.DateTimeField(auto_now_add=True, verbose_name="生成日時")),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_snapshot",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "スクリーニングスナップショット",
                "verbose_name_plural": "スクリーニングスナップショット",
                "db_table": "t_screening_snapshots",
                "indexes": [
                    models.Index(fields=["market_type", "is_active"], name="t_screening_market__b05fca_idx"),
                    models.Index(fields=["market_type", "is_active", "roe"], name="t_screening_market__ef0643_idx"),
                    models.Index(
                        fields=["market_type", "is_active", "dividend_yield"], name="t_screening_market__228748_idx"
                    ),
                    models.Index(fields=["code"], name="t_screening_code_a7e445_idx"),
                ],
            },
        ),
    ]
