# Generated by Django 6.0.2 on 2026-05-13 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="McpApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(default="", max_length=100, verbose_name="ラベル")),
                ("key_prefix", models.CharField(max_length=20, verbose_name="キー識別 prefix")),
                ("key_hash", models.CharField(max_length=128, verbose_name="キー bcrypt ハッシュ")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="最終利用日時")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP APIキー",
                "verbose_name_plural": "MCP APIキー",
                "db_table": "m_mcp_api_keys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["key_prefix", "is_active"], name="idx_mcp_key_prefix"),
                    models.Index(fields=["user", "is_active"], name="idx_mcp_key_user"),
                ],
            },
        ),
    ]
