# Generated by Django 6.0.2 on 2026-05-13 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stocks", "0015_recommendationsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("google_news_rss", "Google News RSS"),
                            ("yfinance", "yfinance"),
                            ("jquants", "J-Quants"),
                        ],
                        max_length=20,
                        verbose_name="ソース",
                    ),
                ),
                ("source_article_id", models.CharField(max_length=255, verbose_name="ソース内記事ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("stock", "個別銘柄"),
                            ("market", "市場・マクロ"),
                            ("fx", "FX・為替"),
                            ("earnings", "決算・IR"),
                        ],
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="タイトル")),
                ("url", models.CharField(max_length=1000, verbose_name="記事URL")),
                ("summary", models.TextField(blank=True, default="", verbose_name="要約")),
                ("publisher", models.CharField(blank=True, default="", max_length=100, verbose_name="発行元")),
                ("language", models.CharField(default="ja", max_length=5, verbose_name="言語")),
                ("published_at", models.DateTimeField(verbose_name="公開日時")),
                ("fetched_at", models.DateTimeField(auto_now_add=True, verbose_name="取り込み日時")),
                ("ai_analyzed_at", models.DateTimeField(blank=True, null=True, verbose_name="AI分析実行日時")),
                (
                    "importance_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="重要度スコア"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "ニュース記事",
                "verbose_name_plural": "ニュース記事",
                "db_table": "t_news_articles",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(fields=["category", "-published_at"], name="idx_news_cat_pub"),
                    models.Index(fields=["-importance_score"], name="idx_news_importance"),
                ],
                "unique_together": {("source", "source_article_id")},
            },
        ),
        migrations.CreateModel(
            name="NewsKeyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[("market", "市場・マクロ"), ("fx", "FX・為替")], max_length=20, verbose_name="カテゴリ"
                    ),
                ),
                ("keyword", models.CharField(max_length=100, verbose_name="キーワード名")),
                ("query", models.CharField(max_length=255, verbose_name="検索クエリ")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("sort_order", models.IntegerField(default=0, verbose_name="並び順")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "ニュース検索キーワード",
                "verbose_name_plural": "ニュース検索キーワード",
                "db_table": "m_news_keywords",
                "ordering": ["category", "sort_order"],
                "unique_together": {("category", "keyword")},
            },
        ),
        migrations.CreateModel(
            name="NewsAiAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "impact_direction",
                    models.CharField(
                        choices=[
                            ("positive", "ポジティブ"),
                            ("negative", "ネガティブ"),
                            ("neutral", "ニュートラル"),
                            ("mixed", "混合"),
                        ],
                        max_length=10,
                        verbose_name="影響方向",
                    ),
                ),
                (
                    "impact_period",
                    models.CharField(
                        choices=[("short", "短期"), ("medium", "中期"), ("long", "長期")],
                        max_length=10,
                        verbose_name="影響期間",
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")], max_length=10, verbose_name="確度"
                    ),
                ),
                ("affected_targets", models.JSONField(default=list, verbose_name="影響対象")),
                ("reasoning", models.TextField(verbose_name="分析理由")),
                ("key_points", models.JSONField(default=list, verbose_name="要点")),
                ("model_used", models.CharField(max_length=100, verbose_name="使用モデル")),
                ("prompt_tokens", models.IntegerField(default=0, verbose_name="プロンプトトークン数")),
                ("completion_tokens", models.IntegerField(default=0, verbose_name="補完トークン数")),
                ("generated_at", models.DateTimeField(verbose_name="生成日時")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = バッチ事前分析, 非NULL = ユーザー要求",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_ai_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="news.newsarticle",
                        verbose_name="ニュース",
                    ),
                ),
            ],
            options={
                "verbose_name": "ニュースAI分析",
                "verbose_name_plural": "ニュースAI分析",
                "db_table": "t_news_ai_analyses",
                "ordering": ["-generated_at"],
                "indexes": [models.Index(fields=["news", "user"], name="idx_news_ai_news_user")],
            },
        ),
        migrations.CreateModel(
            name="NewsStockLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relevance_score", models.DecimalField(decimal_places=2, max_digits=4, verbose_name="関連度スコア")),
                (
                    "matched_by",
                    models.CharField(
                        choices=[
                            ("name_exact_with_context", "銘柄名一致+共起語"),
                            ("name_exact", "銘柄名一致"),
                            ("ticker", "ティッカー一致"),
                            ("name_partial", "銘柄名部分一致"),
                            ("ai_inferred", "AI推定"),
                        ],
                        max_length=30,
                        verbose_name="マッチ種別",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_links",
                        to="news.newsarticle",
                        verbose_name="ニュース",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_links",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "ニュース銘柄リンク",
                "verbose_name_plural": "ニュース銘柄リンク",
                "db_table": "r_news_stocks",
                "indexes": [models.Index(fields=["stock", "news"], name="idx_news_stock_link")],
                "unique_together": {("news", "stock")},
            },
        ),
    ]
