# Generated by Django 6.0.2 on 2026-05-21 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini (BYOK)"),
                            ("openai", "OpenAI (BYOK)"),
                            ("openai_admin", "OpenAI (管理者ロール)"),
                        ],
                        max_length=20,
                        verbose_name="プロバイダー",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200, verbose_name="タイトル")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="開始日時")),
                ("last_message_at", models.DateTimeField(auto_now=True, verbose_name="最終メッセージ日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットセッション",
                "verbose_name_plural": "チャットセッション",
                "db_table": "t_chat_sessions",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "ユーザー"), ("assistant", "アシスタント"), ("tool", "ツール実行結果")],
                        max_length=20,
                        verbose_name="ロール",
                    ),
                ),
                ("content", models.TextField(blank=True, default="", verbose_name="内容")),
                ("tool_name", models.CharField(blank=True, default="", max_length=100, verbose_name="ツール名")),
                ("tool_args", models.JSONField(blank=True, default=dict, verbose_name="ツール引数")),
                ("tool_result", models.JSONField(blank=True, default=dict, verbose_name="ツール実行結果")),
                ("prompt_tokens", models.IntegerField(default=0, verbose_name="プロンプトトークン数")),
                ("completion_tokens", models.IntegerField(default=0, verbose_name="補完トークン数")),
                ("model_used", models.CharField(blank=True, default="", max_length=100, verbose_name="使用モデル")),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gemini", "Google Gemini (BYOK)"),
                            ("openai", "OpenAI (BYOK)"),
                            ("openai_admin", "OpenAI (管理者ロール)"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="プロバイダー",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatsession",
                        verbose_name="セッション",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットメッセージ",
                "verbose_name_plural": "チャットメッセージ",
                "db_table": "t_chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["user", "-last_message_at"], name="t_chat_sess_user_id_98ba56_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["session", "role", "-created_at"], name="t_chat_mess_session_b57e3e_idx"),
        ),
    ]
