# Generated by Django 6.0.2 on 2026-03-23 14:12

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stocks", "0011_add_financial_stock_fy_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperPosition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="保有数")),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14, verbose_name="総取得コスト"
                    ),
                ),
                (
                    "avg_cost_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="平均取得単価"
                    ),
                ),
                (
                    "realized_profit_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14, verbose_name="累積確定損益"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_positions",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_positions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "仮想売買ポジション",
                "verbose_name_plural": "仮想売買ポジション",
                "db_table": "t_paper_positions",
                "unique_together": {("user", "stock")},
            },
        ),
        migrations.CreateModel(
            name="PaperTrade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trade_type", models.CharField(max_length=4, verbose_name="売買種別")),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                ("price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="約定単価")),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="約定金額")),
                (
                    "realized_profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="確定損益"
                    ),
                ),
                (
                    "avg_cost_at_trade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="取引時平均取得単価"
                    ),
                ),
                ("memo", models.CharField(blank=True, default="", max_length=200, verbose_name="メモ")),
                ("traded_at", models.DateTimeField(verbose_name="約定日時")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_trades",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_trades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "仮想売買記録",
                "verbose_name_plural": "仮想売買記録",
                "db_table": "t_paper_trades",
                "ordering": ["-traded_at"],
                "indexes": [models.Index(fields=["user", "stock"], name="t_paper_tra_user_id_16f231_idx")],
            },
        ),
    ]
