# Generated by Django 6.0.2 on 2026-02-25 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Valuation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("calculated_at", models.DateTimeField(auto_now_add=True, verbose_name="算出日時")),
                ("growth_rate", models.DecimalField(decimal_places=4, max_digits=8, verbose_name="成長率")),
                ("fair_pbr", models.DecimalField(decimal_places=4, max_digits=8, verbose_name="適正PBR")),
                ("fair_value", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="適正株価")),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="算出時の現在株価"),
                ),
                ("discount_rate", models.DecimalField(decimal_places=4, max_digits=8, verbose_name="割引/割増率")),
                ("is_undervalued", models.BooleanField(verbose_name="割安判定")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuations",
                        to="stocks.stock",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "適正価格算出結果",
                "verbose_name_plural": "適正価格算出結果",
                "db_table": "valuations",
                "ordering": ["-calculated_at"],
            },
        ),
    ]
