# Generated by Django 6.0.2 on 2026-02-25 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("valuations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="valuation",
            table="t_valuations",
        ),
    ]
