# Generated by Django 6.0.2 on 2026-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("valuations", "0002_alter_valuation_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="valuation",
            name="bps",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="使用BPS"),
        ),
        migrations.AddField(
            model_name="valuation",
            name="cost_of_capital",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="資本コスト"),
        ),
        migrations.AddField(
            model_name="valuation",
            name="current_pbr",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="現在PBR"),
        ),
        migrations.AddField(
            model_name="valuation",
            name="implied_growth_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="市場織り込み成長率"
            ),
        ),
        migrations.AddField(
            model_name="valuation",
            name="roe",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="使用ROE"),
        ),
    ]
