# Generated by Django 6.0.2 on 2026-03-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FxRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pair", models.CharField(default="USDJPY", max_length=10, verbose_name="通貨ペア")),
                ("date", models.DateField(verbose_name="日付")),
                ("close_rate", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="終値")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
            ],
            options={
                "verbose_name": "為替レート",
                "verbose_name_plural": "為替レート",
                "db_table": "t_fx_rates",
                "ordering": ["-date"],
                "unique_together": {("pair", "date")},
            },
        ),
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=5, verbose_name="国コード")),
                ("rate_type", models.CharField(default="10Y", max_length=10, verbose_name="金利種別")),
                ("date", models.DateField(verbose_name="日付")),
                ("rate", models.DecimalField(decimal_places=4, max_digits=8, verbose_name="金利(%)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
            ],
            options={
                "verbose_name": "金利データ",
                "verbose_name_plural": "金利データ",
                "db_table": "t_interest_rates",
                "ordering": ["-date"],
                "unique_together": {("country", "rate_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="MacroIndicator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("indicator_type", models.CharField(max_length=30, verbose_name="指標種別")),
                ("year", models.IntegerField(verbose_name="年")),
                ("value", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="値")),
                ("source", models.CharField(default="OECD", max_length=30, verbose_name="ソース")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "マクロ指標",
                "verbose_name_plural": "マクロ指標",
                "db_table": "m_macro_indicators",
                "ordering": ["-year"],
                "unique_together": {("indicator_type", "year")},
            },
        ),
    ]
